/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'



export function GeckoFooterTest({animationName = 'idle',...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/geckoAnimations.glb')

 const {animations: idleAnimation} = useGLTF('/models/animations/Gecko_Idle_A.glb')
 const {animations: bounceAnimation} = useGLTF('/models/animations/Gecko_Bounce.glb')

  idleAnimation[0].name = 'idle';
  bounceAnimation[0].name = 'bounce';
  console.log(animationName)

  const { actions} = useAnimations([idleAnimation[0],bounceAnimation[0]], group)
   
  useEffect(() => {
    actions[animationName].reset().setEffectiveTimeScale(.4).fadeIn(0.5).play();
    return () => actions[animationName].fadeOut(0.5);
  }, [animationName]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rig" scale={0.4}>
          <skinnedMesh
            name="Mesh"
            geometry={nodes.Mesh.geometry}
            material={materials.M_Gecko}
            skeleton={nodes.Mesh.skeleton}
          />
          <primitive object={nodes.root} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/geckoAnimations.glb')
