/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mofn (https://sketchfab.com/Mofn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-f806c882ecd544be82353c90a2dfe1c6
Title: Bee
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelTest(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bee.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="775001dd263e472b80946e77a01a0163fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.003}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="bee"
                  position={[0, 368.082, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Armature_bee"
                  position={[0, 368.082, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.bee_yellow}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.bee_black}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.bee_wings}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[0, 368.082, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bee.glb')